### ISSUE TITLE
input map with (unphysically) high polarisation quadrupole (or dipole) not recovered in runs

### ISSUE THREAD

**Issue by lukashergt** [hke/Commander#107]
**Disclaimer:** This issue came up during the component separation course AST9240 (so all this is based on that corresponding branch). 
Keep in mind that I am completely new to component separation and commander, so I might not be as precise in formulating this as I'd like to be... Nonetheless, I thought it might be good to summarize what I've been doing for our future selves.

# The issue

I've stumbled over the issue that for an input map with a high (unphysical) polarisation dipole or similarly for a high polarisation quadrupole we don't recover the input map. 

In the next few postings I'll document what modifications I've done and how they affected this issue.

# Current situation <br>(`AST9240_2021_sim` branch)

The below plots are from a run where the dipole map was added to all CMB maps (i.e. I, Q, and U) instead of just to the CMB I map.

![high pol dipole input, not same output](https://user-images.githubusercontent.com/18258042/139316715-e79ee5be-057b-434c-81e5-411466e7deb8.png)

&nbsp; 

![high pol dipole input, ncorr output](https://user-images.githubusercontent.com/18258042/139316839-539f4e0d-de63-4af7-94bd-71cd5e3e0e8a.png)

&nbsp; 

![high pol dipole input, gain output](https://user-images.githubusercontent.com/18258042/139307421-79596a46-dd4e-4734-acd1-0bbe6702588d.png)

**Comment by unfunfunt** [comment]
This was fixed for BP10
